version: '2'
services:
  node1:
    build:
      context: ./node
    container_name: web-node-1
    depends_on:
      - redis
      - mongo
      - rabbitmq
    ports:
      - "3000"
    environment:
      NODE_ID: 1

  node2:
    build:
      context: ./node
    container_name: web-node-2
    depends_on:
      - redis
      - mongo
      - rabbitmq
    ports:
      - "3000"
    environment:
      NODE_ID: 2

  authentication:
    build:
      context: ./authentication
    container_name: authentication
    depends_on:
      - redis
      - mongo
    ports:
      - "3001:3001"

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    links:
      - node1:node1
      - node2:node2
      - authentication:authentication

  redis:
    container_name: redis
    image: redis

  mongo:
    container_name: mongo
    image: mongo

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    environment:
      RABBITMQ_ERLANG_COOKIE: secret cookie here
      RABBITMQ_NODENAME: rabbit
    ports:
      - "8080:15672"

  worker:
    container_name: worker
    build:
      context: ./worker
    depends_on:
      - rabbitmq
  payments:
    container_name: stripe
    build:
      context: ./payments
    depends_on:
      - rabbitmq
    environment:
      STRIPE_API_KEY: sk_test_BQokikJOvBiI2HlWgH4olfQ2
