version: '2'
services:
  node1:
    build: ./node
    container_name: web-node-1
    depends_on:
      - redis
      - mongo
    ports:
      - "3000"
  node2:
    build: ./node
    container_name: web-node-2
    depends_on:
      - redis
      - mongo
    ports:
      - "3000"
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    links:
      - node1:node1
      - node2:node2
  redis:
    container_name: redis
    image: redis
  mongo:
    container_name: mongo
    image: mongo
